export const FORM_CREATE_PROJECT = 'FORM_CREATE_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = "ADD_PROJECT";
export const SHOW_ERROR = "SHOW_ERROR";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ERROR_PROJECT = "ERROR_PROJECT";